use_frameworks!

def shared_pods
pod 'PromiseKit'
pod 'Alamofire'
pod 'KeychainSwift'
pod 'SwiftyJSON'
pod 'YandexMapsMobile', '4.0.0-full'
pod 'IQKeyboardManagerSwift'
end

target 'AutoSpace' do
    shared_pods
end
