# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import ml_pb2 as proto_dot_ml__pb2


class CarDetectorStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.predict = channel.unary_unary(
                '/CarDetector/predict',
                request_serializer=proto_dot_ml__pb2.Image.SerializeToString,
                response_deserializer=proto_dot_ml__pb2.Result.FromString,
                )


class CarDetectorServicer(object):
    """Missing associated documentation comment in .proto file"""

    def predict(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'predict': grpc.unary_unary_rpc_method_handler(
                    servicer.predict,
                    request_deserializer=proto_dot_ml__pb2.Image.FromString,
                    response_serializer=proto_dot_ml__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CarDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CarDetector(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CarDetector/predict',
            proto_dot_ml__pb2.Image.SerializeToString,
            proto_dot_ml__pb2.Result.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
