// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package predictor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CarDetectorClient is the client API for CarDetector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CarDetectorClient interface {
	Predict(ctx context.Context, in *Image, opts ...grpc.CallOption) (*Result, error)
}

type carDetectorClient struct {
	cc grpc.ClientConnInterface
}

func NewCarDetectorClient(cc grpc.ClientConnInterface) CarDetectorClient {
	return &carDetectorClient{cc}
}

func (c *carDetectorClient) Predict(ctx context.Context, in *Image, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/CarDetector/predict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarDetectorServer is the server API for CarDetector service.
// All implementations must embed UnimplementedCarDetectorServer
// for forward compatibility
type CarDetectorServer interface {
	Predict(context.Context, *Image) (*Result, error)
	mustEmbedUnimplementedCarDetectorServer()
}

// UnimplementedCarDetectorServer must be embedded to have forward compatible implementations.
type UnimplementedCarDetectorServer struct {
}

func (UnimplementedCarDetectorServer) Predict(context.Context, *Image) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedCarDetectorServer) mustEmbedUnimplementedCarDetectorServer() {}

// UnsafeCarDetectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CarDetectorServer will
// result in compilation errors.
type UnsafeCarDetectorServer interface {
	mustEmbedUnimplementedCarDetectorServer()
}

func RegisterCarDetectorServer(s *grpc.Server, srv CarDetectorServer) {
	s.RegisterService(&_CarDetector_serviceDesc, srv)
}

func _CarDetector_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Image)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarDetectorServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CarDetector/Predict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarDetectorServer).Predict(ctx, req.(*Image))
	}
	return interceptor(ctx, in, info, handler)
}

var _CarDetector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CarDetector",
	HandlerType: (*CarDetectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "predict",
			Handler:    _CarDetector_Predict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "predictor.proto",
}
